language: node_js
cache:
  directories:
    - node_modules
script:
  - envdotjs --unencrypt && rm env.js.enc && esca-scripts deploy --serverless
notifications:
  email:
    on_success: never
    on_failure: always