service: karnage-warranty-api # NOTE: update this with your service name

custom:
  defaultStage: dev

provider:
  name: aws
  runtime: nodejs6.10
  stage: "${opt:stage, self:custom.defaultStage}"
  region: us-east-2

plugins:
  - serverless-offline

functions:
  postWarrantyRegistration:
    handler: handler.postWarrantyRegistration
    events:
      - http:
          path: warranty-registration
          method: post
          cors: true